#!/usr/bin/env bash
set -euo pipefail

# aet-work orchestrator — generated by aet-work run
# Do not edit by hand; regenerate with: aet-work run
#
# This script is self-contained and uses only bash, git, and python3.
# It reads .agents/work-queue.json, creates worktrees, and invokes the
# detected agent CLI for each unblocked task. Independent tasks execute
# in parallel up to a configurable concurrency cap.

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
QUEUE_FILE="$REPO_ROOT/.agents/work-queue.json"

# ---------------------------------------------------------------------------
# Concurrency cap
# ---------------------------------------------------------------------------

detect_max_jobs() {
  local env_cap
  env_cap="${AET_WORK_JOBS:-}"
  if [ -n "$env_cap" ]; then
    echo "$env_cap"
    return
  fi

  # Fixed default of 4 parallel jobs. Override with AET_WORK_JOBS env var.
  echo "4"
}

MAX_JOBS=$(detect_max_jobs)
if [ "$MAX_JOBS" -gt 8 ]; then
  MAX_JOBS=8
fi
echo "   Concurrency cap: $MAX_JOBS (set AET_WORK_JOBS to override)"

# ---------------------------------------------------------------------------
# Detected CLI configuration — filled in by aet-work run
# ---------------------------------------------------------------------------
CLI_BIN="{{CLI_BIN}}"
CLI_ARGS=({{CLI_ARGS}})
CLI_PROMPT_FLAG="{{CLI_PROMPT_FLAG}}"
CLI_WORKDIR_FLAG="{{CLI_WORKDIR_FLAG}}"

# ---------------------------------------------------------------------------
# Queue helpers (inline python3 — no jq dependency)
# ---------------------------------------------------------------------------

get_next_unblocked() {
  python3 -c "
import json, sys
with open('$QUEUE_FILE', 'r') as f:
    queue = json.load(f)
for task in queue:
    if task.get('status') == 'unblocked':
        print(json.dumps(task))
        sys.exit(0)
sys.exit(1)
"
}

has_pending_tasks() {
  python3 -c "
import json, sys
with open('$QUEUE_FILE', 'r') as f:
    queue = json.load(f)
for task in queue:
    s = task.get('status')
    if s in ('unblocked', 'blocked', 'in-progress'):
        sys.exit(0)
sys.exit(1)
"
}

mark_status() {
  local task_id="$1"
  local status="$2"
  local stage="${3:-}"
  python3 -c "
import json
with open('$QUEUE_FILE', 'r') as f:
    queue = json.load(f)
for task in queue:
    if task['id'] == '$task_id':
        task['status'] = '$status'
        if '$stage':
            task['failed_stage'] = '$stage'
with open('$QUEUE_FILE', 'w') as f:
    json.dump(queue, f, indent=2)
    f.write('\n')
"
}

promote_dependents() {
  python3 -c "
import json
with open('$QUEUE_FILE', 'r') as f:
    queue = json.load(f)
done_ids = {t['id'] for t in queue if t.get('status') in ('done', 'merged', 'merge_verified')}
for task in queue:
    if task.get('status') == 'blocked':
        blockers = task.get('blocked_by', [])
        if all(b in done_ids for b in blockers):
            task['status'] = 'unblocked'
with open('$QUEUE_FILE', 'w') as f:
    json.dump(queue, f, indent=2)
    f.write('\n')
"
}

check_dependency_merged() {
  local task_id="$1"
  python3 -c "
import json, sys
with open('$QUEUE_FILE', 'r') as f:
    queue = json.load(f)
task = next((t for t in queue if t['id'] == '$task_id'), None)
if not task:
    sys.exit(0)
for dep_id in task.get('blocked_by', []):
    dep = next((t for t in queue if t['id'] == dep_id), None)
    if not dep:
        continue
    if dep.get('status') not in ('merged', 'merge_verified'):
        print(f'⚠️  Warning: dependency {dep_id} is not merged. '
              f'This task may build on a stale base. Continuing anyway.')
        sys.stdout.flush()
"
}

record_task_meta() {
  local task_id="$1"
  local worktree_dir="$2"
  local branch="$3"
  python3 -c "
import json
with open('$QUEUE_FILE', 'r') as f:
    queue = json.load(f)
for task in queue:
    if task['id'] == '$task_id':
        task['worktree'] = '$worktree_dir'
        task['branch'] = '$branch'
with open('$QUEUE_FILE', 'w') as f:
    json.dump(queue, f, indent=2)
    f.write('\n')
"
}

clear_worktree_field() {
  local task_id="$1"
  python3 -c "
import json
with open('$QUEUE_FILE', 'r') as f:
    queue = json.load(f)
for task in queue:
    if task['id'] == '$task_id':
        task['worktree'] = None
with open('$QUEUE_FILE', 'w') as f:
    json.dump(queue, f, indent=2)
    f.write('\n')
"
}

remove_empty_worktree() {
  local task_id="$1"
  local worktree_dir="$REPO_ROOT/.worktrees/$task_id"
  if [ ! -d "$worktree_dir" ]; then
    return 0
  fi
  local ahead
  ahead=$(git -C "$worktree_dir" rev-list --count main..HEAD 2>/dev/null || echo 0)
  if [ "$ahead" -eq 0 ]; then
    if git -C "$REPO_ROOT" worktree remove "$worktree_dir" 2>/dev/null; then
      clear_worktree_field "$task_id"
      echo "   🧹 Removed empty worktree for $task_id (0 commits ahead of main)"
    else
      echo "   ⚠️  Empty worktree for $task_id has uncommitted changes; leaving for inspection"
    fi
  fi
}

# ---------------------------------------------------------------------------
# Pre-branch hygiene check
# ---------------------------------------------------------------------------

check_main_hygiene() {
  local repo_root="$1"
  cd "$repo_root"

  # Ensure origin refs are current
  git fetch origin 2>/dev/null || true

  # Check working tree
  if [ -n "$(git status --short)" ]; then
    echo "⚠️  Working tree is dirty. Stash or commit changes before branching."
    return 1
  fi

  # Check unpushed commits
  local ahead
  ahead=$(git rev-list --count origin/main..main 2>/dev/null || echo 0)
  if [ "$ahead" -gt 0 ]; then
    echo "⚠️  Local main is ahead of origin/main by $ahead commit(s)."
    echo "   Push first: git push origin main"
    echo "   Or branch from origin/main explicitly."
    return 1
  fi

  # Check unpulled commits
  local behind
  behind=$(git rev-list --count main..origin/main 2>/dev/null || echo 0)
  if [ "$behind" -gt 0 ]; then
    echo "⚠️  Local main is behind origin/main by $behind commit(s)."
    echo "   Pull first: git pull origin main"
    return 1
  fi

  return 0
}

# ---------------------------------------------------------------------------
# Orphaned in-progress detection
# ---------------------------------------------------------------------------

handle_orphaned_in_progress() {
  python3 -c "
import json, os, sys
with open('$QUEUE_FILE', 'r') as f:
    queue = json.load(f)
changed = False
for task in queue:
    if task.get('status') != 'in-progress':
        continue
    worktree_dir = os.path.join('$REPO_ROOT', '.worktrees', task['id'])
    if os.path.isdir(worktree_dir):
        # Treat as orphaned — no reliable PID tracking across restarts
        print(f\"⚠️  Task {task['id']} is in-progress but worktree exists without a tracked PID.\")
        print(f\"   Marking failed so you can inspect: {worktree_dir}\")
        task['status'] = 'failed'
        task['failed_stage'] = 'orphaned'
        changed = True
if changed:
    with open('$QUEUE_FILE', 'w') as f:
        json.dump(queue, f, indent=2)
        f.write('\n')
"
}

# ---------------------------------------------------------------------------
# Task invocation
# ---------------------------------------------------------------------------

run_task() {
  local plan_file="$1"
  local worktree_dir="$2"

  local prompt="Run aet-pipeline-implement on $REPO_ROOT/$plan_file"
  local cmd=()

  cmd+=("$CLI_BIN")
  if [ ${#CLI_ARGS[@]} -gt 0 ]; then
    cmd+=("${CLI_ARGS[@]}")
  fi
  if [ -n "$CLI_PROMPT_FLAG" ]; then
    cmd+=("$CLI_PROMPT_FLAG" "$prompt")
  else
    cmd+=("$prompt")
  fi
  if [ -n "$CLI_WORKDIR_FLAG" ]; then
    cmd+=("$CLI_WORKDIR_FLAG" "$worktree_dir")
  fi

  echo "   Invoking: ${cmd[*]}"
  cd "$worktree_dir"
  # Signal to skills that they are running unattended under the orchestrator.
  # Skills with interactive approval gates (aet-implement, aet-pipeline-implement)
  # must detect this and skip hard gates that require human input.
  AET_EXECUTION_MODE=unattended "${cmd[@]}"
}

# ---------------------------------------------------------------------------
# Spawn a single task in the background
# ---------------------------------------------------------------------------

spawn_task() {
  local task_json="$1"
  local task_id task_title plan_file worktree_dir

  task_id=$(echo "$task_json" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
  task_title=$(echo "$task_json" | python3 -c "import sys,json; print(json.load(sys.stdin)['title'])")
  plan_file=$(echo "$task_json" | python3 -c "import sys,json; print(json.load(sys.stdin)['plan_file'])")

  echo "▶️  Task: $task_title ($task_id)"
  echo "   Plan: $plan_file"

  # Merge verification
  check_dependency_merged "$task_id"

  # Mark in-progress
  mark_status "$task_id" "in-progress"

  # Worktree setup (idempotent)
  WORKTREE_DIR="$REPO_ROOT/.worktrees/$task_id"
  BRANCH_NAME="$task_id"
  if [ ! -d "$WORKTREE_DIR" ]; then
    echo "   Creating worktree: $WORKTREE_DIR"
    git -C "$REPO_ROOT" worktree add "$WORKTREE_DIR" -b "$BRANCH_NAME"
  else
    echo "   Reusing existing worktree: $WORKTREE_DIR"
  fi
  record_task_meta "$task_id" "$WORKTREE_DIR" "$BRANCH_NAME"

  # Copy untracked plan/PRD files into the worktree so the agent can see them.
  # The git worktree already contains tracked files; we only need untracked ones.
  while IFS= read -r untracked_file; do
    dest="$WORKTREE_DIR/$untracked_file"
    mkdir -p "$(dirname "$dest")"
    cp -p "$REPO_ROOT/$untracked_file" "$dest"
    chmod a-w "$dest"
    echo "   📄 Copied untracked $untracked_file (read-only)"
  done < <(git -C "$REPO_ROOT" ls-files --others --exclude-standard docs/plans/ docs/prds/)

  # Run task in subshell so directory changes don't affect the main loop
  (
    set +e
    run_task "$plan_file" "$WORKTREE_DIR"
    exit $?
  ) &
}

# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------

echo "🚀 aet-work orchestrator starting..."
echo "   Detected CLI: $CLI_BIN"
echo "   Queue file:   $QUEUE_FILE"
echo ""

CURRENT_BRANCH=$(git -C "$REPO_ROOT" branch --show-current)
if [ "$CURRENT_BRANCH" != "main" ]; then
  echo "⚠️  Currently on '$CURRENT_BRANCH', not 'main'. Skipping pre-branch hygiene check."
  echo "   Run 'git checkout main' first if you want worktrees based on a clean, synced main."
else
  if ! check_main_hygiene "$REPO_ROOT"; then
    if [ "${AET_EXECUTION_MODE:-}" = "unattended" ]; then
      echo "   Unattended mode — continuing despite hygiene warnings."
    else
      echo "⛔ Pre-branch hygiene check failed. Halting."
      exit 1
    fi
  fi
fi

echo ""

# Handle orphaned in-progress tasks from a previous run
handle_orphaned_in_progress

# Running job tracking (parallel arrays for bash 3.2 compat)
RUNNING_PIDS=()
RUNNING_TASK_IDS=()
RUNNING_TASK_TITLES=()
SLOTS=0
STOP_SPAWN=0
SUCCESSES=0
FAILURES=0
SKIPPED=0
START_TIME=$(date +%s)

while true; do
  # -----------------------------------------------------------------------
  # Spawn phase: fill available slots with unblocked tasks
  # -----------------------------------------------------------------------
  while [ "$SLOTS" -lt "$MAX_JOBS" ] && [ "$STOP_SPAWN" -eq 0 ]; do
    TASK_JSON=$(get_next_unblocked) || break

    spawn_task "$TASK_JSON"
    PID=$!

    TASK_ID=$(echo "$TASK_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
    TASK_TITLE=$(echo "$TASK_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin)['title'])")

    RUNNING_PIDS+=("$PID")
    RUNNING_TASK_IDS+=("$TASK_ID")
    RUNNING_TASK_TITLES+=("$TASK_TITLE")
    SLOTS=$((SLOTS + 1))
  done

  # -----------------------------------------------------------------------
  # Completion detection: poll for finished background jobs
  # -----------------------------------------------------------------------
  if [ "$SLOTS" -eq 0 ]; then
    # No running jobs
    if [ "$STOP_SPAWN" -eq 1 ]; then
      break
    fi
    if ! has_pending_tasks; then
      break
    fi
    # Tasks are blocked waiting for dependencies; loop will promote them
    # when their blockers finish. Sleep briefly to avoid busy-wait.
    sleep 0.2
    continue
  fi

  FOUND_DONE=0
  for i in "${!RUNNING_PIDS[@]}"; do
    PID="${RUNNING_PIDS[$i]}"
    [ -n "$PID" ] || continue
    if ! kill -0 "$PID" 2>/dev/null; then
      # Job finished — collect exit code
      set +e
      wait "$PID"
      EXIT_CODE=$?
      set -e

      TASK_ID="${RUNNING_TASK_IDS[$i]}"
      TASK_TITLE="${RUNNING_TASK_TITLES[$i]}"

      # Mark slot as empty instead of reindexing (bash 3.2 + set -u safe)
      RUNNING_PIDS[$i]=""
      RUNNING_TASK_IDS[$i]=""
      RUNNING_TASK_TITLES[$i]=""

      SLOTS=$((SLOTS - 1))
      FOUND_DONE=1

      cd "$REPO_ROOT"

      if [ "$EXIT_CODE" -eq 0 ]; then
        echo "   ✅ Task completed successfully"
        mark_status "$TASK_ID" "done"
        python3 -c "
import json
from datetime import datetime
with open('$QUEUE_FILE', 'r') as f:
    queue = json.load(f)
for task in queue:
    if task['id'] == '$TASK_ID':
        task['completed_at'] = datetime.now().isoformat()
with open('$QUEUE_FILE', 'w') as f:
    json.dump(queue, f, indent=2)
    f.write('\n')
"
        promote_dependents
        SUCCESSES=$((SUCCESSES + 1))
      else
        echo "   ❌ Task failed with exit code $EXIT_CODE"
        mark_status "$TASK_ID" "failed" "pipeline"
        STOP_SPAWN=1
        FAILURES=$((FAILURES + 1))
      fi
      remove_empty_worktree "$TASK_ID"

      break  # Handle one completion per outer iteration
    fi
  done

  if [ "$FOUND_DONE" -eq 0 ]; then
    sleep 0.2
  fi

  # If failure stopped spawning and no jobs remain, we're done draining
  if [ "$STOP_SPAWN" -eq 1 ] && [ "$SLOTS" -eq 0 ]; then
    break
  fi
done

END_TIME=$(date +%s)
ELAPSED=$((END_TIME - START_TIME))

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo "🏁 Orchestrator finished."
echo "   Succeeded: $SUCCESSES"
echo "   Failed:    $FAILURES"
echo "   Skipped:   $SKIPPED"
echo "   Elapsed:   ${ELAPSED}s"
echo ""

if [ "$FAILURES" -gt 0 ]; then
  echo "⛔ One or more tasks failed."
  echo "   Run 'aet-work status' to inspect the queue."
  echo "   Run 'aet-work cleanup' to remove merged worktrees."
  exit 1
else
  echo "✅ All tasks complete."
  echo "   Run 'git worktree list' to see active worktrees."
  echo "   Run 'aet-work cleanup' to remove merged worktrees."
  exit 0
fi
