#!/usr/bin/env bash
set -euo pipefail

# aet-work orchestrator — generated by aet-work run
# Do not edit by hand; regenerate with: aet-work run
#
# This script is self-contained and uses only bash, git, and python3.
# It reads .agents/work-queue.json, creates worktrees, and invokes the
# detected agent CLI for each unblocked task sequentially.

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
QUEUE_FILE="$REPO_ROOT/.agents/work-queue.json"

# ---------------------------------------------------------------------------
# Detected CLI configuration — filled in by aet-work run
# ---------------------------------------------------------------------------
CLI_BIN="{{CLI_BIN}}"
CLI_ARGS=({{CLI_ARGS}})
CLI_PROMPT_FLAG="{{CLI_PROMPT_FLAG}}"
CLI_WORKDIR_FLAG="{{CLI_WORKDIR_FLAG}}"

# ---------------------------------------------------------------------------
# Queue helpers (inline python3 — no jq dependency)
# ---------------------------------------------------------------------------

get_next_unblocked() {
  python3 -c "
import json, sys
with open('$QUEUE_FILE', 'r') as f:
    queue = json.load(f)
for task in queue:
    if task.get('status') == 'unblocked':
        print(json.dumps(task))
        sys.exit(0)
sys.exit(1)
"
}

mark_status() {
  local task_id="$1"
  local status="$2"
  local stage="${3:-}"
  python3 -c "
import json
with open('$QUEUE_FILE', 'r') as f:
    queue = json.load(f)
for task in queue:
    if task['id'] == '$task_id':
        task['status'] = '$status'
        if '$stage':
            task['failed_stage'] = '$stage'
with open('$QUEUE_FILE', 'w') as f:
    json.dump(queue, f, indent=2)
    f.write('\n')
"
}

promote_dependents() {
  python3 -c "
import json
with open('$QUEUE_FILE', 'r') as f:
    queue = json.load(f)
done_ids = {t['id'] for t in queue if t.get('status') == 'done'}
for task in queue:
    if task.get('status') == 'blocked':
        blockers = task.get('blocked_by', [])
        if all(b in done_ids for b in blockers):
            task['status'] = 'unblocked'
with open('$QUEUE_FILE', 'w') as f:
    json.dump(queue, f, indent=2)
    f.write('\n')
"
}

check_merge_verified() {
  local task_id="$1"
  python3 -c "
import json, sys
with open('$QUEUE_FILE', 'r') as f:
    queue = json.load(f)
task = next((t for t in queue if t['id'] == '$task_id'), None)
if not task:
    sys.exit(0)
for dep_id in task.get('blocked_by', []):
    dep = next((t for t in queue if t['id'] == dep_id), None)
    if not dep:
        continue
    mv = dep.get('merge_verified')
    if mv is not True:
        print(f'⚠️  Warning: dependency {dep_id} is not merge-verified. '
              f'This task may build on a stale base. Continuing anyway.')
        sys.stdout.flush()
"
}

# ---------------------------------------------------------------------------
# Task invocation
# ---------------------------------------------------------------------------

run_task() {
  local plan_file="$1"
  local worktree_dir="$2"

  local prompt="Run aet-pipeline-implement on $REPO_ROOT/$plan_file"
  local cmd=()

  cmd+=("$CLI_BIN")
  if [ ${#CLI_ARGS[@]} -gt 0 ]; then
    cmd+=("${CLI_ARGS[@]}")
  fi
  if [ -n "$CLI_PROMPT_FLAG" ]; then
    cmd+=("$CLI_PROMPT_FLAG" "$prompt")
  else
    cmd+=("$prompt")
  fi
  if [ -n "$CLI_WORKDIR_FLAG" ]; then
    cmd+=("$CLI_WORKDIR_FLAG" "$worktree_dir")
  fi

  echo "   Invoking: ${cmd[*]}"
  cd "$worktree_dir"
  "${cmd[@]}"
}

# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------

echo "🚀 aet-work orchestrator starting..."
echo "   Detected CLI: $CLI_BIN"
echo "   Queue file:   $QUEUE_FILE"
echo ""

while true; do
  TASK_JSON=$(get_next_unblocked) || {
    echo "✅ No more unblocked tasks. Queue complete."
    break
  }

  TASK_ID=$(echo "$TASK_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
  TASK_TITLE=$(echo "$TASK_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin)['title'])")
  PLAN_FILE=$(echo "$TASK_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin)['plan_file'])")

  echo "▶️  Task: $TASK_TITLE ($TASK_ID)"
  echo "   Plan: $PLAN_FILE"

  # Merge verification
  check_merge_verified "$TASK_ID"

  # Mark in-progress
  mark_status "$TASK_ID" "in-progress"

  # Worktree setup (idempotent)
  WORKTREE_DIR="$REPO_ROOT/.worktrees/$TASK_ID"
  if [ ! -d "$WORKTREE_DIR" ]; then
    echo "   Creating worktree: $WORKTREE_DIR"
    git -C "$REPO_ROOT" worktree add "$WORKTREE_DIR" -b "$TASK_ID"
  else
    echo "   Reusing existing worktree: $WORKTREE_DIR"
  fi

  # Run task
  set +e
  run_task "$PLAN_FILE" "$WORKTREE_DIR"
  EXIT_CODE=$?
  set -e
  cd "$REPO_ROOT"

  if [ $EXIT_CODE -eq 0 ]; then
    echo "   ✅ Task completed successfully"
    mark_status "$TASK_ID" "done"
    promote_dependents
  else
    echo "   ❌ Task failed with exit code $EXIT_CODE"
    mark_status "$TASK_ID" "failed" "pipeline"
    echo ""
    echo "⛔ Orchestrator stopped. Failed task: $TASK_ID"
    echo "   Branch preserved at: $WORKTREE_DIR"
    exit 1
  fi

  echo ""
done

echo ""
echo "🏁 All tasks complete."
echo "   Run 'git worktree list' to see active worktrees."
echo "   Run 'aet-work cleanup' to remove merged worktrees."
